In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pickle
from agent import game_logic

str_step = "010"
with open('snapshots/observation-{}.pkl'.format(str_step), 'rb') as handle:
    observation = pickle.load(handle)
with open('snapshots/game_state-{}.pkl'.format(str_step), 'rb') as handle:
    game_state = pickle.load(handle)
with open('snapshots/missions-{}.pkl'.format(str_step), 'rb') as handle:
    missions = pickle.load(handle)

Loading environment football failed: No module named 'gfootball'


In [3]:
game_logic(game_state, missions, DEBUG=True)

research 2 3
plan mission to build citytile u_1 (1, 3)
attempting action for u_3 (4, 5)
make move u_3 (4, 5) e
actions_by_cities ['r 2 3']
actions_by_units ['m u_3 e']
mission_annotations ['dl 1 3 1 3', 'dc 1 3', 'dl 4 5 10 5', 'dx 10 5', "dst 'U:2 C:2'"]
movement_annotations ['dl 4 5 5 5']


(['r 2 3',
  'm u_3 e',
  'dl 1 3 1 3',
  'dc 1 3',
  'dl 4 5 10 5',
  'dx 10 5',
  "dst 'U:2 C:2'",
  'dl 4 5 5 5'],
 Missions(None,
          {'u_1': <actions.Mission at 0x1047b7e50>,
           'u_3': <actions.Mission at 0x10dd8ec70>}))

In [4]:
import numpy as np
print(np.array(game_state.convolved_rate_matrix))

[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  0  0  0  0  5  0  0  0]
 [ 5  5 10 10  5  0  0  5 10 10  5  5]
 [15 20 15 15  5  0  0  5 15 15 20 15]
 [20 15 10  5  0  0  0  0  5 10 15 20]
 [10 10  0  0  0  0  0  0  0  0 10 10]
 [ 5  0  0  0  0  0  0  0  0  0  0  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]
