In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pickle
from agent import game_logic

str_step = "090"
with open('snapshots/observation-{}.pkl'.format(str_step), 'rb') as handle:
    observation = pickle.load(handle)
with open('snapshots/game_state-{}.pkl'.format(str_step), 'rb') as handle:
    game_state = pickle.load(handle)
with open('snapshots/missions-{}.pkl'.format(str_step), 'rb') as handle:
    missions = pickle.load(handle)

Loading environment football failed: No module named 'gfootball'


In [3]:
_ = game_logic(game_state, missions, DEBUG=True)

plan mission to build citytile u_4 (0, 3)
plan mission to build citytile u_5 (3, 1)
plan mission to build citytile u_7 (2, 10)
plan mission to build citytile u_12 (0, 8)
attempting action for u_4 (0, 1)
make move u_4 (0, 1) n
attempting action for u_5 (1, 1)
make move u_5 (1, 1) n
attempting action for u_7 (2, 10)
location reached and make action u_7 (2, 10)
attempting action for u_9 (2, 2)
make move u_9 (2, 2) e
attempting action for u_14 (1, 9)
make move u_14 (1, 9) e
actions_by_cities []
actions_by_units ['m u_4 n', 'm u_5 n', 'bcity u_7', 'm u_9 e', 'm u_14 e']
mission_annotations ['dl 0 1 0 3', 'dc 0 3', 'dl 2 10 2 10', 'dc 2 10', 'dl 0 5 0 11', 'dx 0 11', 'dl 0 10 0 8', 'dc 0 8', 'dl 1 1 3 1', 'dc 3 1', 'dl 4 4 6 9', 'dx 6 9', 'dl 1 6 6 8', 'dx 6 8', 'dl 2 2 7 2', 'dx 7 2', 'dl 1 9 5 4', 'dx 5 4', 'dl 2 6 7 8', 'dx 7 8', "dst 'U:10 C:10'"]
movement_annotations ['dl 0 1 0 0', 'dl 1 1 1 0', 'dl 2 2 3 2', 'dl 1 9 2 9']


In [4]:
import numpy as np
print(np.array(game_state.convolved_rate_matrix))

[[ 15  15   5   0   0   0   0   0   0   0   0   0]
 [ 15  15   5   0   0   0  50  50   0   0   0   0]
 [  5   5   0   0   0  50 150 150  50   0   0   0]
 [  0   0   0   0   0  50 200 150  50   0   0   0]
 [  0   0   0   0   0  50 100 100   0   0   0   0]
 [  0   0   0   0   0   0  50   0   0   0   0   0]
 [  0   0   0   0   0   0  50   0   0   0   0   0]
 [  0   0   0   0   0  50 100 100   0   0   0   0]
 [  0   0   0   0   0  50 200 150  50   0   0   0]
 [  5   5   0   0   0  50 150 150  50   0   0   0]
 [ 15  15   5   0   0   0  50  50   0   0   0   0]
 [ 15  15   5   0   0   0   0   0   0   0   0   0]]
