In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pickle
from agent import game_logic

str_step = "090"
with open('snapshots/game_state-{}.pkl'.format(str_step), 'rb') as handle:
    game_state = pickle.load(handle)
with open('snapshots/missions-{}.pkl'.format(str_step), 'rb') as handle:
    missions = pickle.load(handle)

In [3]:
_ = game_logic(game_state, missions, DEBUG=True)

unit_limit_exceeded c_18 (6, 6)
research (6, 6)
build_worker c_18 5 5 1 10
plan mission adaptative u_1 (7, 6) -> (0, 6)
plan mission adaptative u_6 (6, 5) -> (0, 5)
plan mission adaptative u_7 (5, 5) -> (1, 3)
plan mission adaptative u_9 (7, 3) -> (0, 2)
plan mission adaptative u_10 (4, 4) -> (0, 4)
plan mission adaptative u_14 (8, 5) -> (0, 3)
plan mission adaptative u_16 (6, 4) -> (7, 4)
check False 6 20 True
plan mission to build citytile u_18 (7, 4) -> (1, 4)
attempting action for u_1 (7, 6)
attempting action for u_3 (1, 4)
location reached and make action u_3 (1, 4)
attempting action for u_4 (1, 8)
location reached and make action u_4 (1, 8)
attempting action for u_6 (6, 5)
make move u_6 (6, 5) w
attempting action for u_7 (5, 5)
make move u_7 (5, 5) w
attempting action for u_9 (7, 3)
make move u_9 (7, 3) w
attempting action for u_10 (4, 4)
attempting action for u_14 (8, 5)
attempting action for u_16 (6, 4)
attempting action for u_17 (2, 6)
make move u_17 (2, 6) s
attempting action

In [4]:
import numpy as np
print(game_state.convolved_collectable_tiles_matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [2 1 0 0 0 1 0 1 0 0 0 0]
 [2 1 0 0 1 1 2 1 1 0 0 0]
 [1 0 0 0 0 1 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [2 1 0 0 0 0 0 0 0 0 0 0]
 [2 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
